// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: membershipmodule/membership/events.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// EventMemberEnrolled is an event emitted when a new member is enrolled
type EventMemberEnrolled struct {
	MemberAddress string `protobuf:"bytes,1,opt,name=member_address,json=memberAddress,proto3" json:"member_address,omitempty"`
}

func (m *EventMemberEnrolled) Reset()         { *m = EventMemberEnrolled{} }
func (m *EventMemberEnrolled) String() string { return proto.CompactTextString(m) }
func (*EventMemberEnrolled) ProtoMessage()    {}
func (*EventMemberEnrolled) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0ec29745b3464b1, []int{0}
}
func (m *EventMemberEnrolled) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventMemberEnrolled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventMemberEnrolled.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventMemberEnrolled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMemberEnrolled.Merge(m, src)
}
func (m *EventMemberEnrolled) XXX_Size() int {
	return m.Size()
}
func (m *EventMemberEnrolled) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMemberEnrolled.DiscardUnknown(m)
}

var xxx_messageInfo_EventMemberEnrolled proto.InternalMessageInfo

func (m *EventMemberEnrolled) GetMemberAddress() string {
	if m != nil {
		return m.MemberAddress
	}
	return ""
}

// EventMemberStatusChanged is an event emitted when a member's citizenship
// status changes
type EventMemberStatusChanged struct {
	MemberAddress  string           `protobuf:"bytes,1,opt,name=member_address,json=memberAddress,proto3" json:"member_address,omitempty"`
	Status         MembershipStatus `protobuf:"varint,2,opt,name=status,proto3,enum=membershipmodule.membership.MembershipStatus" json:"status,omitempty"`
	PreviousStatus MembershipStatus `protobuf:"varint,3,opt,name=previous_status,json=previousStatus,proto3,enum=membershipmodule.membership.MembershipStatus" json:"previous_status,omitempty"`
	Operator       string           `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
}

func (m *EventMemberStatusChanged) Reset()         { *m = EventMemberStatusChanged{} }
func (m *EventMemberStatusChanged) String() string { return proto.CompactTextString(m) }
func (*EventMemberStatusChanged) ProtoMessage()    {}
func (*EventMemberStatusChanged) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0ec29745b3464b1, []int{1}
}
func (m *EventMemberStatusChanged) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventMemberStatusChanged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventMemberStatusChanged.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventMemberStatusChanged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMemberStatusChanged.Merge(m, src)
}
func (m *EventMemberStatusChanged) XXX_Size() int {
	return m.Size()
}
func (m *EventMemberStatusChanged) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMemberStatusChanged.DiscardUnknown(m)
}

var xxx_messageInfo_EventMemberStatusChanged proto.InternalMessageInfo

func (m *EventMemberStatusChanged) GetMemberAddress() string {
	if m != nil {
		return m.MemberAddress
	}
	return ""
}

func (m *EventMemberStatusChanged) GetStatus() MembershipStatus {
	if m != nil {
		return m.Status
	}
	return MembershipStatus_MemberStatusEmpty
}

func (m *EventMemberStatusChanged) GetPreviousStatus() MembershipStatus {
	if m != nil {
		return m.PreviousStatus
	}
	return MembershipStatus_MemberStatusEmpty
}

func (m *EventMemberStatusChanged) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

// EventMemberGrantedGuardianship is an event emitted when a member's guardianship status is granted
type EventMemberGrantedGuardianship struct {
	MemberAddress string `protobuf:"bytes,1,opt,name=member_address,json=memberAddress,proto3" json:"member_address,omitempty"`
}

func (m *EventMemberGrantedGuardianship) Reset()         { *m = EventMemberGrantedGuardianship{} }
func (m *EventMemberGrantedGuardianship) String() string { return proto.CompactTextString(m) }
func (*EventMemberGrantedGuardianship) ProtoMessage()    {}
func (*EventMemberGrantedGuardianship) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0ec29745b3464b1, []int{2}
}
func (m *EventMemberGrantedGuardianship) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventMemberGrantedGuardianship) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventMemberGrantedGuardianship.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventMemberGrantedGuardianship) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMemberGrantedGuardianship.Merge(m, src)
}
func (m *EventMemberGrantedGuardianship) XXX_Size() int {
	return m.Size()
}
func (m *EventMemberGrantedGuardianship) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMemberGrantedGuardianship.DiscardUnknown(m)
}

var xxx_messageInfo_EventMemberGrantedGuardianship proto.InternalMessageInfo

func (m *EventMemberGrantedGuardianship) GetMemberAddress() string {
	if m != nil {
		return m.MemberAddress
	}
	return ""
}

// EventMemberRevokedGuardianship is an event emitted when a member's guardianship status is revoked
type EventMemberRevokedGuardianship struct {
	MemberAddress string `protobuf:"bytes,1,opt,name=member_address,json=memberAddress,proto3" json:"member_address,omitempty"`
}

func (m *EventMemberRevokedGuardianship) Reset()         { *m = EventMemberRevokedGuardianship{} }
func (m *EventMemberRevokedGuardianship) String() string { return proto.CompactTextString(m) }
func (*EventMemberRevokedGuardianship) ProtoMessage()    {}
func (*EventMemberRevokedGuardianship) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0ec29745b3464b1, []int{3}
}
func (m *EventMemberRevokedGuardianship) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventMemberRevokedGuardianship) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventMemberRevokedGuardianship.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventMemberRevokedGuardianship) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventMemberRevokedGuardianship.Merge(m, src)
}
func (m *EventMemberRevokedGuardianship) XXX_Size() int {
	return m.Size()
}
func (m *EventMemberRevokedGuardianship) XXX_DiscardUnknown() {
	xxx_messageInfo_EventMemberRevokedGuardianship.DiscardUnknown(m)
}

var xxx_messageInfo_EventMemberRevokedGuardianship proto.InternalMessageInfo

func (m *EventMemberRevokedGuardianship) GetMemberAddress() string {
	if m != nil {
		return m.MemberAddress
	}
	return ""
}

type EventTotalVotingWeightChanged struct {
	// Old total voting weight
	OldTotalVotingWeight github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=old_total_voting_weight,json=oldTotalVotingWeight,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"old_total_voting_weight,omitempty"`
	// New total voting weight
	NewTotalVotingWeight github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=new_total_voting_weight,json=newTotalVotingWeight,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"new_total_voting_weight,omitempty"`
}

func (m *EventTotalVotingWeightChanged) Reset()         { *m = EventTotalVotingWeightChanged{} }
func (m *EventTotalVotingWeightChanged) String() string { return proto.CompactTextString(m) }
func (*EventTotalVotingWeightChanged) ProtoMessage()    {}
func (*EventTotalVotingWeightChanged) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0ec29745b3464b1, []int{4}
}
func (m *EventTotalVotingWeightChanged) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventTotalVotingWeightChanged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventTotalVotingWeightChanged.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventTotalVotingWeightChanged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventTotalVotingWeightChanged.Merge(m, src)
}
func (m *EventTotalVotingWeightChanged) XXX_Size() int {
	return m.Size()
}
func (m *EventTotalVotingWeightChanged) XXX_DiscardUnknown() {
	xxx_messageInfo_EventTotalVotingWeightChanged.DiscardUnknown(m)
}

var xxx_messageInfo_EventTotalVotingWeightChanged proto.InternalMessageInfo

func init() {
	proto.RegisterType((*EventMemberEnrolled)(nil), "membershipmodule.membership.EventMemberEnrolled")
	proto.RegisterType((*EventMemberStatusChanged)(nil), "membershipmodule.membership.EventMemberStatusChanged")
	proto.RegisterType((*EventMemberGrantedGuardianship)(nil), "membershipmodule.membership.EventMemberGrantedGuardianship")
	proto.RegisterType((*EventMemberRevokedGuardianship)(nil), "membershipmodule.membership.EventMemberRevokedGuardianship")
	proto.RegisterType((*EventTotalVotingWeightChanged)(nil), "membershipmodule.membership.EventTotalVotingWeightChanged")
}

func init() {
	proto.RegisterFile("membershipmodule/membership/events.proto", fileDescriptor_b0ec29745b3464b1)
}

var fileDescriptor_b0ec29745b3464b1 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x41, 0x8b, 0xd3, 0x40,
	0x14, 0xc7, 0x3b, 0x55, 0x16, 0x1d, 0xb4, 0x42, 0x5c, 0xb0, 0x54, 0x4c, 0xd7, 0x82, 0xd2, 0x83,
	0x4d, 0x40, 0x4f, 0x82, 0x17, 0x57, 0x4b, 0x4f, 0x7b, 0x49, 0x65, 0x05, 0x2f, 0x61, 0xda, 0x79,
	0x24, 0xc3, 0x26, 0xf3, 0xc2, 0xcc, 0x24, 0x75, 0xbf, 0x82, 0x27, 0xbf, 0x8e, 0xdf, 0x60, 0x8f,
	0x7b, 0x14, 0x0f, 0x45, 0xda, 0x9b, 0x9f, 0xc1, 0x83, 0x64, 0xa6, 0xbb, 0x1b, 0x5d, 0x77, 0x59,
	0x7a, 0xca, 0x9b, 0x3f, 0xff, 0xf7, 0x7b, 0xff, 0x49, 0xf2, 0xe8, 0x30, 0x87, 0x7c, 0x06, 0x4a,
	0xa7, 0xa2, 0xc8, 0x91, 0x97, 0x19, 0x84, 0x17, 0x42, 0x08, 0x15, 0x48, 0xa3, 0x83, 0x42, 0xa1,
	0x41, 0xef, 0xf1, 0xbf, 0xce, 0xe0, 0x42, 0xe8, 0xed, 0x26, 0x98, 0xa0, 0xf5, 0x85, 0x75, 0xe5,
	0x5a, 0x7a, 0xd7, 0xc2, 0x5d, 0xe9, 0x9c, 0x83, 0x37, 0xf4, 0xe1, 0xb8, 0x1e, 0x76, 0x60, 0xc5,
	0xb1, 0x54, 0x98, 0x65, 0xc0, 0xbd, 0x67, 0xb4, 0xe3, 0x6c, 0x31, 0xe3, 0x5c, 0x81, 0xd6, 0x5d,
	0xb2, 0x47, 0x86, 0x77, 0xa3, 0xfb, 0x4e, 0x7d, 0xeb, 0xc4, 0xc1, 0x6f, 0x42, 0xbb, 0x8d, 0xf6,
	0xa9, 0x61, 0xa6, 0xd4, 0xef, 0x52, 0x26, 0x93, 0x1b, 0x33, 0xbc, 0x31, 0xdd, 0xd1, 0xb6, 0xaf,
	0xdb, 0xde, 0x23, 0xc3, 0xce, 0xcb, 0x51, 0x70, 0xcd, 0x7d, 0x83, 0x83, 0xf3, 0xd2, 0x0d, 0x8b,
	0x36, 0xcd, 0xde, 0x21, 0x7d, 0x50, 0x28, 0xa8, 0x04, 0x96, 0x3a, 0xde, 0xf0, 0x6e, 0x6d, 0xc3,
	0xeb, 0x9c, 0x51, 0xdc, 0xd9, 0xeb, 0xd1, 0x3b, 0x58, 0x80, 0x62, 0x06, 0x55, 0xf7, 0xb6, 0xcd,
	0x7f, 0x7e, 0x1e, 0x4c, 0xa8, 0xdf, 0xb8, 0xfd, 0x44, 0x31, 0x69, 0x80, 0x4f, 0x4a, 0xa6, 0xb8,
	0x60, 0xb2, 0x66, 0xde, 0xf4, 0x3d, 0xfe, 0x0d, 0x8a, 0xa0, 0xc2, 0xa3, 0xed, 0x40, 0xdf, 0xda,
	0xf4, 0x89, 0x25, 0x7d, 0x40, 0xc3, 0xb2, 0x43, 0x34, 0x42, 0x26, 0x1f, 0x41, 0x24, 0xa9, 0x39,
	0xfb, 0x2a, 0x5f, 0x08, 0x7d, 0x84, 0x19, 0x8f, 0x4d, 0x6d, 0x88, 0x2b, 0xeb, 0x88, 0x17, 0xd6,
	0x62, 0x91, 0xf7, 0xf6, 0xa7, 0x27, 0xcb, 0x7e, 0xeb, 0xc7, 0xb2, 0xff, 0x3c, 0x11, 0x26, 0x2d,
	0x67, 0xc1, 0x1c, 0xf3, 0x70, 0x8e, 0x3a, 0x47, 0xbd, 0x79, 0x8c, 0x34, 0x3f, 0x0a, 0xcd, 0x71,
	0x01, 0x3a, 0x78, 0x0f, 0xf3, 0x5f, 0xcb, 0xfe, 0xd3, 0x2b, 0x80, 0x2f, 0x30, 0x17, 0x06, 0xf2,
	0xc2, 0x1c, 0x47, 0xbb, 0x98, 0xf1, 0x4b, 0x99, 0x6c, 0x18, 0x09, 0x8b, 0xff, 0x86, 0x69, 0x6f,
	0x1b, 0xe6, 0x0a, 0x60, 0x33, 0x8c, 0x84, 0xc5, 0xa5, 0x30, 0xfb, 0xd3, 0x93, 0x95, 0x4f, 0x4e,
	0x57, 0x3e, 0xf9, 0xb9, 0xf2, 0xc9, 0xd7, 0xb5, 0xdf, 0x3a, 0x5d, 0xfb, 0xad, 0xef, 0x6b, 0xbf,
	0xf5, 0xe9, 0x75, 0x63, 0xb8, 0x44, 0x25, 0xd8, 0x48, 0x82, 0x09, 0xdd, 0xcf, 0x34, 0x6a, 0x6c,
	0xd6, 0xe7, 0xe6, 0x9a, 0xd9, 0x4c, 0xb3, 0x1d, 0xbb, 0x66, 0xaf, 0xfe, 0x04, 0x00, 0x00, 0xff,
	0xff, 0xee, 0x71, 0x15, 0xe8, 0xef, 0x03, 0x00, 0x00,
}

func (m *EventMemberEnrolled) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventMemberEnrolled) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventMemberEnrolled) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MemberAddress) > 0 {
		i -= len(m.MemberAddress)
		copy(dAtA[i:], m.MemberAddress)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.MemberAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventMemberStatusChanged) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventMemberStatusChanged) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventMemberStatusChanged) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0x22
	}
	if m.PreviousStatus != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.PreviousStatus))
		i--
		dAtA[i] = 0x18
	}
	if m.Status != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x10
	}
	if len(m.MemberAddress) > 0 {
		i -= len(m.MemberAddress)
		copy(dAtA[i:], m.MemberAddress)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.MemberAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventMemberGrantedGuardianship) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventMemberGrantedGuardianship) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventMemberGrantedGuardianship) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MemberAddress) > 0 {
		i -= len(m.MemberAddress)
		copy(dAtA[i:], m.MemberAddress)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.MemberAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventMemberRevokedGuardianship) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventMemberRevokedGuardianship) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventMemberRevokedGuardianship) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MemberAddress) > 0 {
		i -= len(m.MemberAddress)
		copy(dAtA[i:], m.MemberAddress)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.MemberAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventTotalVotingWeightChanged) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventTotalVotingWeightChanged) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventTotalVotingWeightChanged) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.NewTotalVotingWeight.Size()
		i -= size
		if _, err := m.NewTotalVotingWeight.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.OldTotalVotingWeight.Size()
		i -= size
		if _, err := m.OldTotalVotingWeight.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEvents(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventMemberEnrolled) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MemberAddress)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventMemberStatusChanged) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MemberAddress)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.Status != 0 {
		n += 1 + sovEvents(uint64(m.Status))
	}
	if m.PreviousStatus != 0 {
		n += 1 + sovEvents(uint64(m.PreviousStatus))
	}
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventMemberGrantedGuardianship) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MemberAddress)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventMemberRevokedGuardianship) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MemberAddress)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *EventTotalVotingWeightChanged) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.OldTotalVotingWeight.Size()
	n += 1 + l + sovEvents(uint64(l))
	l = m.NewTotalVotingWeight.Size()
	n += 1 + l + sovEvents(uint64(l))
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventMemberEnrolled) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventMemberEnrolled: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventMemberEnrolled: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemberAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MemberAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventMemberStatusChanged) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventMemberStatusChanged: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventMemberStatusChanged: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemberAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MemberAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= MembershipStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousStatus", wireType)
			}
			m.PreviousStatus = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PreviousStatus |= MembershipStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventMemberGrantedGuardianship) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventMemberGrantedGuardianship: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventMemberGrantedGuardianship: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemberAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MemberAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventMemberRevokedGuardianship) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventMemberRevokedGuardianship: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventMemberRevokedGuardianship: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemberAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MemberAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventTotalVotingWeightChanged) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventTotalVotingWeightChanged: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventTotalVotingWeightChanged: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OldTotalVotingWeight", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OldTotalVotingWeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewTotalVotingWeight", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NewTotalVotingWeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
